name: publish
on: 
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - production.json
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
              docker build . --tag ghcr.io/fnts-public/pa11y-dashboard:latest
              docker push ghcr.io/fnts-public/pa11y-dashboard:latest